# We will use docker to set up out environment, so don't use any particular
# language in Travis itself
language: generic

# Enable docker
sudo: required
services:
    - docker

# Disable automatic submodule fetching (it's done recursively)
git:
    submodules: false

# Do a shallow submodule fetch
before_install: git submodule update --init

# Global environment variables
env:
    global:
        - DIST=xenial
        # Make sure beaver is in the PATH
        - PATH="$(git config -f .gitmodules submodule.beaver.path)/bin:$PATH"

jobs:
    templates:
        - &test-matrix
          stage: Test
          after_success: beaver dlang codecov
          script:
              - set -e # Do not continue on failure
              - beaver dlang install
              - beaver dlang make
        - &package-matrix
          stage: Build and upload packages
          if: tag IS present
          script:
              - set -e # Do not continue on failure
              - beaver dlang install
              - beaver dlang make
              - beaver dlang make pkg
              - beaver bintray upload -d sociomantic-tsunami/nodes/dhtnode build/production/pkg/*.deb

    include:
        # Test matrix
        - <<: *test-matrix
          env: DMD=1.082.* F=production COV=1
        - <<: *test-matrix
          env: DMD=1.082.* F=devel COV=1
        - <<: *test-matrix
          env: DMD=2.071.2.s* F=production COV=1
        - <<: *test-matrix
          env: DMD=2.071.2.s* F=devel COV=1

        # Package matrix
        - <<: *package-matrix
          env: DMD=1.082.* F=production COV=0
        - <<: *package-matrix
          env: DMD=2.071.2.s* F=production COV=0
